package ie.gmit.bio.kmer;

public enum AminoAcidAlphabet {
	//Alphabets generated by simulated annealing with heuristic Multiclass MCC in range [-0.0001...1]
	SA_Murphy4 (4), //0.6721142989707685
	SA_Murphy5 (5), //0.49578499457826347
	SA_Murphy6 (6), //0.42017464279163674
	SA_Murphy8 (8), //0.40564564795265734
	SA_Murphy10 (10), //0.8326753876096891
	SA_Murphy12 (12), //0.8463889571892524
	SA_Murphy15 (15), //0.8148271447167919
	SA_Wang2 (2), //0.31587951878120496
	SA_Wang3 (3), //0.6616525812262266
	SA_Wang5 (5), //0.3112037607217347
	SA_Wang5Variant (5), //0.4036756626007117
	SA_Li3 (3), //0.6617196325955078
	SA_Li4 (4), //0.7038672163942313
	SA_Li10 (10), //0.8221951446464185
	SA_Buchfink11 (11), //0.8199078277704395		
	SA_Random2 (2), //0.23895000852422932
	SA_Random3 (3), //0.5647771399034532
	SA_Random4 (4), //0.63528055690816
	SA_Random5 (5), //0.4397908067169635
	SA_Random6 (6), //0.43437524167993136
	SA_Random7 (7), //0.42635397130590463
	SA_Random8 (8), //0.4171613411553377
	SA_Random9 (9), //0.7981632882555734
	SA_Random10 (10), //0.8076892270573981
	SA_Random11 (11), //0.8087401879494348
	SA_Random12 (12), //0.7898233329205829
	SA_Random13 (13), //0.7921228354643544
	SA_Random14 (14), //0.7872714300042105
	SA_Random15 (15), //0.8081659908753297
	SA_Random16 (16), //0.7959255041000655
	
	
	//Alphabets optimised for specific AMPs
	AMP_OPTIMISED_LECTIN_15 (15),
	AMP_OPTIMISED_HISTONE_15 (15),
	AMP_OPTIMISED_SNAKIN_13 (13),
	AMP_OPTIMISED_THIONIN_13 (13),
	AMP_OPTIMISED_BREVININ_13 (13),
	AMP_OPTIMISED_TEMPORIN_13 (13),
	AMP_OPTIMISED_TEMPORIN_11 (11),
	AMP_OPTIMISED_THIONIN_9 (9),
	
	
	//Thionin Alphabets optimised for specific AMPs (March 2021)
	THIONIN_VARIATION_I_2(2),
	THIONIN_VARIATION_II_2(2),
	THIONIN_VARIATION_III_4(4),
	THIONIN_VARIATION_IV_5(5),
	THIONIN_VARIATION_V_5(5),
	
	
	//Temporin Alphabets optimised for specific AMPs (March 2021)
	TEMPORIN_VARIATION_I_2(2),
	TEMPORIN_VARIATION_II_3(3),
	TEMPORIN_VARIATION_III_3(3),
	TEMPORIN_VARIATION_IV_6(6),
	TEMPORIN_VARIATION_V_5(5),
	
	
	//Variations from JalView using Clustal (March 29th 2021)
	THIONIN_CLUSTAL_15 (15),
	TEMPORIN_CLUSTAL_16 (16),
	
	
	//Variations from JalView using Clustal (April 20th 2021)
	THIONIN_CLUSTAL_10 (10),
	THIONIN_CLUSTAL_12 (12),
	THIONIN_CLUSTAL_14 (14),
	TEMPORIN_CLUSTAL_10 (10),
	TEMPORIN_CLUSTAL_12 (12),
	TEMPORIN_CLUSTAL_14 (14),

	
	
	//Published Amino Acid Alphabets
	PolarHydophobic2 (2), 
	Wang2 (2), 
	Li3 (3), 
	Wang3 (3), 
	Li4 (4), 
	Murphy4 (4), 
	Li5 (5), 
	Murphy5 (5), 
	Wang5 (5), 
	Wang5Variant (5), 
	PhysicoChemical5 (5), 
	Murphy6 (6), 
	PhysicoChemical6 (6), 
	Murphy8 (8), 
	Li10 (10), 
	Murphy10 (10), 
	Buchfink11 (11), 
	Murphy12 (12), 
	Murphy15 (15), 
	Murphy18 (18),
	IUPAC20 (20);

	private final int symbols;

    private AminoAcidAlphabet(int symbols) {
        this.symbols = symbols;
    }
	
    public int getSymbolsCount() {
        return this.symbols;
    }
}